### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Xnhyacinth** [facebookresearch/FiD#32]
when I run the code test_reader.py for test, it shows that there is an error in src/model.py
ModuleNotFoundError: No module named 'fused_layer_norm_cuda'

**Comment by szh-max** [comment]
是否是apex没有下载为cuda版本？

**Comment by szh-max** [comment]
@Xnhyacinth 请问是你否将FiD应用于中文数据集，我进行尝试，但是准确率不太可以

**Comment by Xnhyacinth** [comment]
> 是否是apex没有下载为cuda版本？

貌似是apex的问题，我直接卸载了就行了

**Comment by Xnhyacinth** [comment]
> @Xnhyacinth 请问是你否将FiD应用于中文数据集，我进行尝试，但是准确率不太可以

T5中文是不大行吧，试试glm？
