### ISSUE TITLE
Running FiD with fp16 precision

### ISSUE THREAD

**Issue by huvunvidia** [facebookresearch/FiD#9]
Hi, we wonder if you have implemented a fp16 version of this model? We tried to implement it ourselves, but it doesn't work. The loss reduces for hundreds steps and then increase again. We tried both the NVIDIA Apex AMP and Pytorch Native AMP but none of them works. We wonder if you have implemented yourself and whether it behaves as expected.
Thank you very much. We appreciate your works.

**Comment by gizacard** [comment]
Hi, I had a similar experience: I tried to use PyTorch mixed precision and noticed instability and didn't try to push it further.
